### ISSUE TITLE
the method debug_traceTransaction does not exist/is not available

### ISSUE THREAD

**Issue by dipakitaliya** [oasysgames/verse-layer-optimism#10]
I have been running geth node using. 
when I try to run debug_traceTransaction It gives the error message  "the method debug_traceTransaction does not exist/is not available".

also when I try to run oasys-blockscout. The indexer service throws the same error. due to this indexing does not complete. keep getting on explorer is  "Indexing Tokens - We're indexing this chain right now. Some of the counts may be inaccurate."

`2022-12-24T06:09:58.749 application=indexer fetcher=internal_transaction count=6 error_count=6 [error] Failed to fetch internal transactions for blocks: [%{code: -32601, data: %{block_number: 1, transaction_hash: "0xb0663e19bf53fa830f5aa1082bf25cef899ca50b916949921904bda80331b1d4", transaction_index: 0}, message: "the method debug_traceTransaction does not exist/is not available"}]`

your support will really help and I appreciate it.

**Comment by tak1827** [comment]
Please add the `debug` value to the `--http.api option` of geth:
https://geth.ethereum.org/docs/interacting-with-geth/rpc

If you're using a Docker file, please append `debug` to `RPC_API`.
